#' Plot inference result from the VCCP model
#'
#' \code{getTestPlot} plots the possible change points in the vine
#' copula structure of a multivariate time series and their
#' significance generated by a VCCP model.
#'
#' @param vccp_result A list generated from \code{\link{vccp.fun}}.
#'
#' @export
#' @examples
#' data = cbind(1:180, random.mvn.simulate.2.changes(180,8,seed=101))
#' result = vccp.fun(data, "NBS", test = "V")
#' getTestPlot(result)
#'
#' result.2 = vccp.fun(data, "NBS", test = "B")
#' getTestPlot(result.2)
#' @seealso \code{\link{VCCP}}
getTestPlot <- function(vccp_result){
  if(length(vccp_result)==0){
    return(cat("Inappropriate VCCP model specification!"))
  }else{
    if(dim(vccp_result$test.df)[2]==4){
      GetTestPlot.Boot(vccp_result$test.df, vccp_result$T)
    }else{
      GetTestPlot.Vuong(vccp_result$test.df, vccp_result$T,
                        vccp_result$sig_alpha)
    }
  }
}
